import Head from 'next/head';
import Link from 'next/link';

import Button from '../components/Button'
import SkillCard from '../components/SkillCard';
import WorkCard from '../components/WorkCard';

export default function Home() {
  return (
    <>
      <Head>
        <title>Owenltm | Mobile & Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero flex flex-col justify-center">
        <div className="flex justify-between px-36">
          <div className="self-center">
            <div className="mb-12">
              <h1 className="mb-4 text-4xl">Hello, my name is <span className="font-semibold">Owen Lwiantoro</span></h1>
              <h1 className="text-5xl font-semibold">Mobile & Web Developer</h1>
            </div>

            <Button customClass="border border-black bg-black text-white inline-block hover:bg-white hover:text-black">
              <Link href="/#work"><a>My work</a></Link>
            </Button>
          </div>

          <div className="flex flex-col justify-center items-end space-y-4">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" viewBox="0 0 20 20" fill="currentColor">
              <path d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z" />
            </svg>
            <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" viewBox="0 0 20 20" fill="currentColor">
              <path d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z" />
            </svg>
            <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" viewBox="0 0 20 20" fill="currentColor">
              <path d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z" />
            </svg>
          </div>
        </div>
      </div>
      <section id="about">
        <div className="grid grid-cols-2 justify-items-end items-center">
          <div className="">
            <h2 className="section-title mb-8">About Me</h2>
            <p>Hello, my name is Owen Lwiantoro. I am currently studying at Bina Nusantara University, majoring in Mobile Application and Technology. My goal is to develop application that have good design and easy to use.</p>
          </div>
          <div className="rounded-xl overflow-hidden">
            <img className="" src="https://picsum.photos/id/1005/250" alt="LOL"/>
          </div>
        </div>
      </section>
      <section>
        <h2 className="section-title mb-4">My Skills</h2>
        <div className="skill-list">
          <SkillCard imageUrl="https://picsum.photos/id/1005/100" title="SKILL" />
          <SkillCard imageUrl="https://picsum.photos/id/1005/100" title="SKILL" />
          <SkillCard imageUrl="https://picsum.photos/id/1005/100" title="SKILL" />
        </div>
      </section>
      <section id="work">
        <h2 className="section-title mb-4">My Works</h2>
        <div className="work-list">
          <WorkCard imageUrl="https://picsum.photos/id/1005/300/225" title="Work Title" subTitle="Integer pretium ipsum ac commodo iaculis. Maecenas non neque ac eros placerat posuere sit amet eu est. Mauris convallis eu sem id condimentum. Curabitur porttitor consequat sapien euismod volutpat." />
          <WorkCard imageUrl="https://picsum.photos/id/1005/300/225" title="Work Title" subTitle="Integer pretium ipsum ac commodo iaculis. Maecenas non neque ac eros placerat posuere sit amet eu est. Mauris convallis eu sem id condimentum. Curabitur porttitor consequat sapien euismod volutpat." />
          <WorkCard imageUrl="https://picsum.photos/id/1005/300/225" title="Work Title" subTitle="Integer pretium ipsum ac commodo iaculis. Maecenas non neque ac eros placerat posuere sit amet eu est. Mauris convallis eu sem id condimentum. Curabitur porttitor consequat sapien euismod volutpat." />
        </div>
      </section>
      <section id="contact">
        {
          //TODO: CONTACT SECTION
        }
        <h1>Contact</h1>
      </section>
      <div className="px-36 py-3">
        <p className="">©Owenltm - 2021</p>
      </div>
    </>
  )
}
